version: "3.9"

services:
  promptly-ngnix:
    image: nginx:mainline-alpine
    container_name: promptly-ngnix
    ports:
      - "80:80"
    networks:
      - promptly-net
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
networks:
  promptly-net:
    external: true
