name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend (Go)
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run tests
      run: go test ./...
    
    - name: Build
      run: go build -o promptly cmd/promptly/main.go
    
    - name: Verify binary
      run: ./promptly --help

  frontend:
    name: Frontend (SvelteKit)
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: promptly-web/package-lock.json
    
    - name: Install dependencies
      working-directory: promptly-web
      run: npm ci
    
    - name: Build frontend
      working-directory: promptly-web
      run: npm run build
    
    - name: Check TypeScript
      working-directory: promptly-web
      run: npx tsc --noEmit